-- Extra guidance content (warmup / cardio / cooldown + a title + estimated
-- duration) for a single workout_routines row, generated by the new
-- weekday-based AI routine feature (src/lib/aiRoutine/). One-to-one with a
-- routine: the trackable "workout" section of that same generation still
-- lives in workout_exercises as always (created via the existing
-- createRoutine/createExercise), so Move's set-checking UI needs no changes
-- at all — this table only adds read-only context alongside it. Deleting
-- the parent routine cascades here too.
--
-- Not applied automatically — run via `supabase db push` or paste into the
-- Supabase SQL editor. Safe to re-run.

create table if not exists public.routine_day_details (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  routine_id uuid not null unique references public.workout_routines (id) on delete cascade,
  title text not null,
  estimated_minutes int,
  -- Each an array of {name, durationOrReps} / {name, durationSeconds, targetArea}.
  warmup jsonb not null default '[]'::jsonb,
  cooldown jsonb not null default '[]'::jsonb,
  -- {type, minutes, intensity} — null when the day has no separate cardio.
  cardio jsonb,
  created_at timestamptz not null default now()
);

create index if not exists routine_day_details_user_idx on public.routine_day_details (user_id);

alter table public.routine_day_details enable row level security;

create policy "routine_day_details: select own rows" on public.routine_day_details for select using (auth.uid() = user_id);
create policy "routine_day_details: insert own rows" on public.routine_day_details for insert with check (auth.uid() = user_id);
create policy "routine_day_details: update own rows" on public.routine_day_details for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "routine_day_details: delete own rows" on public.routine_day_details for delete using (auth.uid() = user_id);
